### ISSUE TITLE
Validação ocorrendo em parte do registro

### ISSUE THREAD

**Issue by mozgbrasil** [cyberglot/bradoc#11]
Boa Tarde

Ola tudo bem

Estou efetuando um teste

E tenho o seguinte CPF valido

316.328.549-02

Mas ao utilizar sua biblioteca e informar qualquer coisa a partir do ultimo numero, também é retornado como valido

Caso que venha a informar

316.328.549-02x

Retorna true

-

#!/usr/bin/env node

const bradoc = require('bradoc');

var isValid = bradoc.cpf.validate('316.328.549-02x'); 

console.log(isValid);

**Comment by pabloocastro** [comment]
@mozgbrasil Realmente ocorre este problema. Pelo que identifiquei na analise do código o fato ocorre na utilização da função **deformat** do arquivo _valid.js_. Essa função remove toda a máscara da variável passada para ele deixando apenas números. O problema é que o regex utilizado remove tudo que não for número e isso faz com que a lib aceite o caso que você passou como exemplo.

Isso pode ser observado neste trecho de código:
Linhas: 39 e 40 do arquivo _valid.js_
`var regex = /[^0-9]+/g;`
 `doc = doc.replace(regex, '');`
